# Generated by Django 2.0.4 on 2018-05-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256)),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o2m.Todo'),
        ),
    ]
